### ISSUE TITLE
Cannot make the sample app

### ISSUE THREAD

**Issue by avi1810** [open-ness/specs#12]
When i try to make th sample application i get this error
![dd](https://user-images.githubusercontent.com/61222801/75216411-ede51100-57b9-11ea-92b6-3212f1e482e6.PNG)

**Comment by amr-mokhtar** [comment]
Hi @avi1810, this problem is experienced when using golang 1.13.x version. This fix will become available in next release. In order to overcome this error execute the following:
```shell
$ go mod init sample-app
$ cd sample-app
$ make
```
