### ISSUE TITLE
Error while installing OpenNESS On-Premises

### ISSUE THREAD

**Issue by ishanVshah** [open-ness/specs#14]
fatal: [xxxx-xx.xxxxxx.x86-01]: FAILED! => {"changed": false, "cmd": "/usr/bin/gmake build", "msg": "mysql uses an image, skipping\nBuilding cups-ui\nBuilding ui\nBuilding cnca-ui\nBuilding cce\nService 'cce' failed to build: The command '/bin/sh -c apk add git' returned a non-zero code: 1\ngmake: *** [build] Error 1", "rc": 2, "stderr": "mysql uses an image, skipping\nBuilding cups-ui\nBuilding ui\nBuilding cnca-ui\nBuilding cce\nService 'cce' failed to build: The command '/bin/sh -c apk add git' returned a non-zero code: 1\ngmake: *** [build] Error 1\n", "stderr_lines": ["mysql uses an image, skipping", "Building cups-ui", "Building ui", "Building cnca-ui", "Building cce", "Service 'cce' failed to build: The command '/bin/sh -c apk add git' returned a non-zero code: 1", "gmake: *** [build] Error 1"], "stdout": "docker-compose build\nStep 1/20 : FROM node:lts-alpine AS cups-ui-deps-image\n ---> 927d03058714\nStep 2/20 : WORKDIR /usr/src/app\n ---> Using cache\n ---> fb254ead378b\nStep 3/20 : COPY ./server/package.json ./server/yarn.lock ./\n ---> Using cache\n ---> 7c67677a227a\nStep 4/20 : RUN yarn install --pure-lockfile --production\n ---> Using cache\n ---> 1b0ccaa051c6\nStep 5/20 : COPY ./server ./\n ---> Using cache\n ---> 09c7e40250d7\nStep 6/20 : WORKDIR /app\n ---> Using cache\n ---> 80f7f30377b9\nStep 7/20 : COPY package.json yarn.lock ./\n ---> Using cache\n ---> 09434d79e657\nStep 8/20 : RUN yarn install --pure-lockfile --production\n ---> Using cache\n ---> 8ef7e110a78e\n\nStep 9/20 : FROM cups-ui-deps-image\n ---> 8ef7e110a78e\nStep 10/20 : ARG REACT_APP_CUPS_API\n ---> Using cache\n ---> 8daa77da178d\nStep 11/20 : ENV REACT_APP_CUPS_API=$REACT_APP_CUPS_API\n ---> Using cache\n ---> a955d538ec96\nStep 12/20 : ARG CONTROLLER_UI_URL\n ---> Using cache\n ---> 255e5cada90d\nStep 13/20 : ENV REACT_APP_CONTROLLER_UI_URL=$CONTROLLER_UI_URL\n ---> Running in 14414fc111a8\nRemoving intermediate container 14414fc111a8\n ---> a7d4deac0695\nStep 14/20 : ENV INLINE_RUNTIME_CHUNK=false\n ---> Running in c556216bfabe\nRemoving intermediate container c556216bfabe\n ---> 0cf7f720de89\nStep 15/20 : COPY . ./\n ---> 004ad17975d8\nStep 16/20 : RUN yarn build\n ---> Running in dfdcb3c30205\nyarn run v1.22.0\n$ react-scripts build\nCreating an optimized production build...\n\u001b[91mBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`\n\u001b[0mCompiled successfully.\n\nFile sizes after gzip:\n\n  185.58 KB  build/static/js/2.e2121035.chunk.js\n  4.27 KB    build/static/js/main.12c5224c.chunk.js\n  762 B      build/static/js/runtime~main.a8a9905a.js\n  580 B      build/static/css/2.94155858.chunk.css\n  138 B      build/static/css/main.090348ab.chunk.css\n\nThe project was built assuming it is hosted at the server root.\nYou can control this with the homepage field in your package.json.\nFor example, add this to build it for GitHub Pages:\n\n  \"homepage\" : \"http://myname.github.io/myapp\",\n\nThe build folder is ready to be deployed.\nYou may serve it with a static server:\n\n  yarn global add serve\n  serve -s build\n\nFind out more about deployment here:\n\n  https://bit.ly/CRA-deploy\n\nDone in 39.23s.\nRemoving intermediate container dfdcb3c30205\n ---> 7dda5ce1e18e\nStep 17/20 : WORKDIR /usr/src/app\n ---> Running in d24c2188be5f\nRemoving intermediate container d24c2188be5f\n ---> 85e1ceaaf4e5\nStep 18/20 : RUN cp -r /app/build ./build\n ---> Running in f7e20ad5a440\nRemoving intermediate container f7e20ad5a440\n ---> 8a7d6c099e5b\nStep 19/20 : EXPOSE 80\n ---> Running in dcdaa8923bc0\nRemoving intermediate container dcdaa8923bc0\n ---> e356b30e21e2\nStep 20/20 : CMD [\"node\", \"server.js\"]\n ---> Running in fde18b2ba558\nRemoving intermediate container fde18b2ba558\n ---> 37064adb739e\n\nSuccessfully built 37064adb739e\nSuccessfully tagged cups:latest\nStep 1/26 : FROM node:lts-alpine AS cce-ui-deps-image\n ---> 927d03058714\nStep 2/26 : WORKDIR /usr/src/app\n ---> Using cache\n ---> fb254ead378b\nStep 3/26 : COPY ./server/package.json ./server/yarn.lock ./\n ---> Using cache\n ---> 7c67677a227a\nStep 4/26 : RUN yarn install --pure-lockfile --production\n ---> Using cache\n ---> 1b0ccaa051c6\nStep 5/26 : COPY ./server ./\n ---> Using cache\n ---> 84396d6fcaed\nStep 6/26 : WORKDIR /app\n ---> Using cache\n ---> ff7dc78d1677\nStep 7/26 : COPY package.json yarn.lock ./\n ---> Using cache\n ---> 95cd3842345c\nStep 8/26 : RUN yarn install --pure-lockfile --production\n ---> Using cache\n ---> 37418efac03b\n\nStep 9/26 : FROM cce-ui-deps-image\n ---> 37418efac03b\nStep 10/26 : ARG CCE_ORCHESTRATION_MODE\n ---> Using cache\n ---> 60d8ca8d639b\nStep 11/26 : ENV REACT_APP_ORCHESTRATION_MODE=$CCE_ORCHESTRATION_MODE\n ---> Using cache\n ---> b6fc30473dc6\nStep 12/26 : ARG REACT_APP_CONTROLLER_API\n ---> Using cache\n ---> 1e186b2c6222\nStep 13/26 : ENV REACT_APP_CONTROLLER_API=$REACT_APP_CONTROLLER_API\n ---> Using cache\n ---> 403b4f5501e5\nStep 14/26 : ARG CONTROLLER_UI_URL\n ---> Using cache\n ---> c1f7eeef1d93\nStep 15/26 : ENV REACT_APP_CONTROLLER_UI_URL=$CONTROLLER_UI_URL\n ---> Using cache\n ---> 9d334f862812\nStep 16/26 : ARG CNCA_UI_URL\n ---> Using cache\n ---> 9e6c894526f3\nStep 17/26 : ENV REACT_APP_CNCA_UI_URL=$CNCA_UI_URL\n ---> Using cache\n ---> 39dc6b9818df\nStep 18/26 : ARG CUPS_UI_URL\n ---> Using cache\n ---> 238d9a74b461\nStep 19/26 : ENV REACT_APP_CUPS_UI_URL=$CUPS_UI_URL\n ---> Using cache\n ---> 1d58dda10207\nStep 20/26 : ENV INLINE_RUNTIME_CHUNK=false\n ---> Using cache\n ---> 029f0a42ab0c\nStep 21/26 : COPY . ./\n ---> Using cache\n ---> 89fff0c71311\nStep 22/26 : RUN yarn build\n ---> Using cache\n ---> 4a45a6072e37\nStep 23/26 : WORKDIR /usr/src/app\n ---> Using cache\n ---> 5f720deaed1b\nStep 24/26 : RUN cp -r /app/build ./build\n ---> Using cache\n ---> 779361689b52\nStep 25/26 : EXPOSE 80\n ---> Using cache\n ---> e2f119dcee9e\nStep 26/26 : CMD [\"node\", \"server.js\"]\n ---> Using cache\n ---> 33397079ae6f\n\n[Warning] One or more build-args [REACT_APP_ORCHESTRATION_MODE] were not consumed\nSuccessfully built 33397079ae6f\nSuccessfully tagged ui:latest\nStep 1/22 : FROM node:lts-alpine AS cnca-ui-deps-image\n ---> 927d03058714\nStep 2/22 : WORKDIR /usr/src/app\n ---> Using cache\n ---> fb254ead378b\nStep 3/22 : COPY ./server/package.json ./server/yarn.lock ./\n ---> Using cache\n ---> 7c67677a227a\nStep 4/22 : RUN yarn install --pure-lockfile --production\n ---> Using cache\n ---> 1b0ccaa051c6\nStep 5/22 : COPY ./server ./\n ---> Using cache\n ---> cf8b715cf65e\nStep 6/22 : WORKDIR /app\n ---> Using cache\n ---> c2cdb3b2b966\nStep 7/22 : COPY package.json yarn.lock ./\n ---> Using cache\n ---> a0b7a8e7e8a5\nStep 8/22 : RUN yarn install --pure-lockfile --production\n ---> Using cache\n ---> e159f3541aa0\n\nStep 9/22 : FROM cnca-ui-deps-image\n ---> e159f3541aa0\nStep 10/22 : ARG REACT_APP_CNCA_AF_API\n ---> Using cache\n ---> f5d6d3ac2a45\nStep 11/22 : ENV REACT_APP_CNCA_AF_API=$REACT_APP_CNCA_AF_API\n ---> Using cache\n ---> e397c1d9b4af\nStep 12/22 : ARG REACT_APP_CNCA_5GOAM_API\n ---> Using cache\n ---> ec6e8745c974\nStep 13/22 : ENV REACT_APP_CNCA_5GOAM_API=$REACT_APP_CNCA_5GOAM_API\n ---> Using cache\n ---> 3c984fe474b1\nStep 14/22 : ARG CONTROLLER_UI_URL\n ---> Using cache\n ---> 9bbac8107a74\nStep 15/22 : ENV REACT_APP_CONTROLLER_UI_URL=$CONTROLLER_UI_URL\n ---> Running in bf2257973d4f\nRemoving intermediate container bf2257973d4f\n ---> 31ea4be9b42b\nStep 16/22 : ENV INLINE_RUNTIME_CHUNK=false\n ---> Running in 5fd76e432544\nRemoving intermediate container 5fd76e432544\n ---> 220052d0cdef\nStep 17/22 : COPY . ./\n ---> e21285a73647\nStep 18/22 : RUN yarn build\n ---> Running in d0730b0d5a76\nyarn run v1.22.0\n$ react-scripts build\nCreating an optimized production build...\n\u001b[91mBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`\n\u001b[0mCompiled successfully.\n\nFile sizes after gzip:\n\n  186.03 KB  build/static/js/2.78149bfa.chunk.js\n  6.01 KB    build/static/js/main.c5d45c5a.chunk.js\n  762 B      build/static/js/runtime~main.a8a9905a.js\n  580 B      build/static/css/2.94155858.chunk.css\n  138 B      build/static/css/main.090348ab.chunk.css\n\nThe project was built assuming it is hosted at the server root.\nYou can control this with the homepage field in your package.json.\nFor example, add this to build it for GitHub Pages:\n\n  \"homepage\" : \"http://myname.github.io/myapp\",\n\nThe build folder is ready to be deployed.\nYou may serve it with a static server:\n\n  yarn global add serve\n  serve -s build\n\nFind out more about deployment here:\n\n  https://bit.ly/CRA-deploy\n\nDone in 39.20s.\nRemoving intermediate container d0730b0d5a76\n ---> 1e5161f5d11b\nStep 19/22 : WORKDIR /usr/src/app\n ---> Running in 1ebf15e6202f\nRemoving intermediate container 1ebf15e6202f\n ---> 2f4bd93a9e34\nStep 20/22 : RUN cp -r /app/build ./build\n ---> Running in 5c6b91419d2a\nRemoving intermediate container 5c6b91419d2a\n ---> f910b393fd38\nStep 21/22 : EXPOSE 80\n ---> Running in 7e09d8805ed2\nRemoving intermediate container 7e09d8805ed2\n ---> 7af1186e0062\nStep 22/22 : CMD [\"node\", \"server.js\"]\n ---> Running in 09b0a7a5d444\nRemoving intermediate container 09b0a7a5d444\n ---> 2bedc4ea4e74\n\nSuccessfully built 2bedc4ea4e74\nSuccessfully tagged cnca:latest\nStep 1/15 : FROM golang:1.12-alpine\n ---> 76bddfb5e55e\nStep 2/15 : ENV GO111MODULE on\n ---> Using cache\n ---> 4dfe2d41c6e4\nStep 3/15 : WORKDIR /go/src/github.com/open-ness/edgecontroller\n ---> Using cache\n ---> d9832e91215b\nStep 4/15 : RUN apk add git\n ---> Running in 134d0a63f240\nfetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz\n\u001b[91mERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)\nWARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory\n\u001b[0mfetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz\n\u001b[91mERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)\nWARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory\n\u001b[0m\u001b[91mERROR: unsatisfiable constraints:\n\u001b[0m  git (missing):\n    required by: world[git]\n", "stdout_lines": ["docker-compose build", "Step 1/20 : FROM node:lts-alpine AS cups-ui-deps-image", " ---> 927d03058714", "Step 2/20 : WORKDIR /usr/src/app", " ---> Using cache", " ---> fb254ead378b", "Step 3/20 : COPY ./server/package.json ./server/yarn.lock ./", " ---> Using cache", " ---> 7c67677a227a", "Step 4/20 : RUN yarn install --pure-lockfile --production", " ---> Using cache", " ---> 1b0ccaa051c6", "Step 5/20 : COPY ./server ./", " ---> Using cache", " ---> 09c7e40250d7", "Step 6/20 : WORKDIR /app", " ---> Using cache", " ---> 80f7f30377b9", "Step 7/20 : COPY package.json yarn.lock ./", " ---> Using cache", " ---> 09434d79e657", "Step 8/20 : RUN yarn install --pure-lockfile --production", " ---> Using cache", " ---> 8ef7e110a78e", "", "Step 9/20 : FROM cups-ui-deps-image", " ---> 8ef7e110a78e", "Step 10/20 : ARG REACT_APP_CUPS_API", " ---> Using cache", " ---> 8daa77da178d", "Step 11/20 : ENV REACT_APP_CUPS_API=$REACT_APP_CUPS_API", " ---> Using cache", " ---> a955d538ec96", "Step 12/20 : ARG CONTROLLER_UI_URL", " ---> Using cache", " ---> 255e5cada90d", "Step 13/20 : ENV REACT_APP_CONTROLLER_UI_URL=$CONTROLLER_UI_URL", " ---> Running in 14414fc111a8", "Removing intermediate container 14414fc111a8", " ---> a7d4deac0695", "Step 14/20 : ENV INLINE_RUNTIME_CHUNK=false", " ---> Running in c556216bfabe", "Removing intermediate container c556216bfabe", " ---> 0cf7f720de89", "Step 15/20 : COPY . ./", " ---> 004ad17975d8", "Step 16/20 : RUN yarn build", " ---> Running in dfdcb3c30205", "yarn run v1.22.0", "$ react-scripts build", "Creating an optimized production build...", "\u001b[91mBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`", "\u001b[0mCompiled successfully.", "", "File sizes after gzip:", "", "  185.58 KB  build/static/js/2.e2121035.chunk.js", "  4.27 KB    build/static/js/main.12c5224c.chunk.js", "  762 B      build/static/js/runtime~main.a8a9905a.js", "  580 B      build/static/css/2.94155858.chunk.css", "  138 B      build/static/css/main.090348ab.chunk.css", "", "The project was built assuming it is hosted at the server root.", "You can control this with the homepage field in your package.json.", "For example, add this to build it for GitHub Pages:", "", "  \"homepage\" : \"http://myname.github.io/myapp\",", "", "The build folder is ready to be deployed.", "You may serve it with a static server:", "", "  yarn global add serve", "  serve -s build", "", "Find out more about deployment here:", "", "  https://bit.ly/CRA-deploy", "", "Done in 39.23s.", "Removing intermediate container dfdcb3c30205", " ---> 7dda5ce1e18e", "Step 17/20 : WORKDIR /usr/src/app", " ---> Running in d24c2188be5f", "Removing intermediate container d24c2188be5f", " ---> 85e1ceaaf4e5", "Step 18/20 : RUN cp -r /app/build ./build", " ---> Running in f7e20ad5a440", "Removing intermediate container f7e20ad5a440", " ---> 8a7d6c099e5b", "Step 19/20 : EXPOSE 80", " ---> Running in dcdaa8923bc0", "Removing intermediate container dcdaa8923bc0", " ---> e356b30e21e2", "Step 20/20 : CMD [\"node\", \"server.js\"]", " ---> Running in fde18b2ba558", "Removing intermediate container fde18b2ba558", " ---> 37064adb739e", "", "Successfully built 37064adb739e", "Successfully tagged cups:latest", "Step 1/26 : FROM node:lts-alpine AS cce-ui-deps-image", " ---> 927d03058714", "Step 2/26 : WORKDIR /usr/src/app", " ---> Using cache", " ---> fb254ead378b", "Step 3/26 : COPY ./server/package.json ./server/yarn.lock ./", " ---> Using cache", " ---> 7c67677a227a", "Step 4/26 : RUN yarn install --pure-lockfile --production", " ---> Using cache", " ---> 1b0ccaa051c6", "Step 5/26 : COPY ./server ./", " ---> Using cache", " ---> 84396d6fcaed", "Step 6/26 : WORKDIR /app", " ---> Using cache", " ---> ff7dc78d1677", "Step 7/26 : COPY package.json yarn.lock ./", " ---> Using cache", " ---> 95cd3842345c", "Step 8/26 : RUN yarn install --pure-lockfile --production", " ---> Using cache", " ---> 37418efac03b", "", "Step 9/26 : FROM cce-ui-deps-image", " ---> 37418efac03b", "Step 10/26 : ARG CCE_ORCHESTRATION_MODE", " ---> Using cache", " ---> 60d8ca8d639b", "Step 11/26 : ENV REACT_APP_ORCHESTRATION_MODE=$CCE_ORCHESTRATION_MODE", " ---> Using cache", " ---> b6fc30473dc6", "Step 12/26 : ARG REACT_APP_CONTROLLER_API", " ---> Using cache", " ---> 1e186b2c6222", "Step 13/26 : ENV REACT_APP_CONTROLLER_API=$REACT_APP_CONTROLLER_API", " ---> Using cache", " ---> 403b4f5501e5", "Step 14/26 : ARG CONTROLLER_UI_URL", " ---> Using cache", " ---> c1f7eeef1d93", "Step 15/26 : ENV REACT_APP_CONTROLLER_UI_URL=$CONTROLLER_UI_URL", " ---> Using cache", " ---> 9d334f862812", "Step 16/26 : ARG CNCA_UI_URL", " ---> Using cache", " ---> 9e6c894526f3", "Step 17/26 : ENV REACT_APP_CNCA_UI_URL=$CNCA_UI_URL", " ---> Using cache", " ---> 39dc6b9818df", "Step 18/26 : ARG CUPS_UI_URL", " ---> Using cache", " ---> 238d9a74b461", "Step 19/26 : ENV REACT_APP_CUPS_UI_URL=$CUPS_UI_URL", " ---> Using cache", " ---> 1d58dda10207", "Step 20/26 : ENV INLINE_RUNTIME_CHUNK=false", " ---> Using cache", " ---> 029f0a42ab0c", "Step 21/26 : COPY . ./", " ---> Using cache", " ---> 89fff0c71311", "Step 22/26 : RUN yarn build", " ---> Using cache", " ---> 4a45a6072e37", "Step 23/26 : WORKDIR /usr/src/app", " ---> Using cache", " ---> 5f720deaed1b", "Step 24/26 : RUN cp -r /app/build ./build", " ---> Using cache", " ---> 779361689b52", "Step 25/26 : EXPOSE 80", " ---> Using cache", " ---> e2f119dcee9e", "Step 26/26 : CMD [\"node\", \"server.js\"]", " ---> Using cache", " ---> 33397079ae6f", "", "[Warning] One or more build-args [REACT_APP_ORCHESTRATION_MODE] were not consumed", "Successfully built 33397079ae6f", "Successfully tagged ui:latest", "Step 1/22 : FROM node:lts-alpine AS cnca-ui-deps-image", " ---> 927d03058714", "Step 2/22 : WORKDIR /usr/src/app", " ---> Using cache", " ---> fb254ead378b", "Step 3/22 : COPY ./server/package.json ./server/yarn.lock ./", " ---> Using cache", " ---> 7c67677a227a", "Step 4/22 : RUN yarn install --pure-lockfile --production", " ---> Using cache", " ---> 1b0ccaa051c6", "Step 5/22 : COPY ./server ./", " ---> Using cache", " ---> cf8b715cf65e", "Step 6/22 : WORKDIR /app", " ---> Using cache", " ---> c2cdb3b2b966", "Step 7/22 : COPY package.json yarn.lock ./", " ---> Using cache", " ---> a0b7a8e7e8a5", "Step 8/22 : RUN yarn install --pure-lockfile --production", " ---> Using cache", " ---> e159f3541aa0", "", "Step 9/22 : FROM cnca-ui-deps-image", " ---> e159f3541aa0", "Step 10/22 : ARG REACT_APP_CNCA_AF_API", " ---> Using cache", " ---> f5d6d3ac2a45", "Step 11/22 : ENV REACT_APP_CNCA_AF_API=$REACT_APP_CNCA_AF_API", " ---> Using cache", " ---> e397c1d9b4af", "Step 12/22 : ARG REACT_APP_CNCA_5GOAM_API", " ---> Using cache", " ---> ec6e8745c974", "Step 13/22 : ENV REACT_APP_CNCA_5GOAM_API=$REACT_APP_CNCA_5GOAM_API", " ---> Using cache", " ---> 3c984fe474b1", "Step 14/22 : ARG CONTROLLER_UI_URL", " ---> Using cache", " ---> 9bbac8107a74", "Step 15/22 : ENV REACT_APP_CONTROLLER_UI_URL=$CONTROLLER_UI_URL", " ---> Running in bf2257973d4f", "Removing intermediate container bf2257973d4f", " ---> 31ea4be9b42b", "Step 16/22 : ENV INLINE_RUNTIME_CHUNK=false", " ---> Running in 5fd76e432544", "Removing intermediate container 5fd76e432544", " ---> 220052d0cdef", "Step 17/22 : COPY . ./", " ---> e21285a73647", "Step 18/22 : RUN yarn build", " ---> Running in d0730b0d5a76", "yarn run v1.22.0", "$ react-scripts build", "Creating an optimized production build...", "\u001b[91mBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`", "\u001b[0mCompiled successfully.", "", "File sizes after gzip:", "", "  186.03 KB  build/static/js/2.78149bfa.chunk.js", "  6.01 KB    build/static/js/main.c5d45c5a.chunk.js", "  762 B      build/static/js/runtime~main.a8a9905a.js", "  580 B      build/static/css/2.94155858.chunk.css", "  138 B      build/static/css/main.090348ab.chunk.css", "", "The project was built assuming it is hosted at the server root.", "You can control this with the homepage field in your package.json.", "For example, add this to build it for GitHub Pages:", "", "  \"homepage\" : \"http://myname.github.io/myapp\",", "", "The build folder is ready to be deployed.", "You may serve it with a static server:", "", "  yarn global add serve", "  serve -s build", "", "Find out more about deployment here:", "", "  https://bit.ly/CRA-deploy", "", "Done in 39.20s.", "Removing intermediate container d0730b0d5a76", " ---> 1e5161f5d11b", "Step 19/22 : WORKDIR /usr/src/app", " ---> Running in 1ebf15e6202f", "Removing intermediate container 1ebf15e6202f", " ---> 2f4bd93a9e34", "Step 20/22 : RUN cp -r /app/build ./build", " ---> Running in 5c6b91419d2a", "Removing intermediate container 5c6b91419d2a", " ---> f910b393fd38", "Step 21/22 : EXPOSE 80", " ---> Running in 7e09d8805ed2", "Removing intermediate container 7e09d8805ed2", " ---> 7af1186e0062", "Step 22/22 : CMD [\"node\", \"server.js\"]", " ---> Running in 09b0a7a5d444", "Removing intermediate container 09b0a7a5d444", " ---> 2bedc4ea4e74", "", "Successfully built 2bedc4ea4e74", "Successfully tagged cnca:latest", "Step 1/15 : FROM golang:1.12-alpine", " ---> 76bddfb5e55e", "Step 2/15 : ENV GO111MODULE on", " ---> Using cache", " ---> 4dfe2d41c6e4", "Step 3/15 : WORKDIR /go/src/github.com/open-ness/edgecontroller", " ---> Using cache", " ---> d9832e91215b", "Step 4/15 : RUN apk add git", " ---> Running in 134d0a63f240", "fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz", "\u001b[91mERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/main: temporary error (try again later)", "WARNING: Ignoring APKINDEX.70f61090.tar.gz: No such file or directory", "\u001b[0mfetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz", "\u001b[91mERROR: http://dl-cdn.alpinelinux.org/alpine/v3.11/community: temporary error (try again later)", "WARNING: Ignoring APKINDEX.ca2fea5b.tar.gz: No such file or directory", "\u001b[0m\u001b[91mERROR: unsatisfiable constraints:", "\u001b[0m  git (missing):", "    required by: world[git]"]}

**Comment by amr-mokhtar** [comment]
Hi @ishanVshah,
Is this problem still valid?

**Comment by ishanVshah** [comment]
REsolved.
