### ISSUE TITLE
The links to images in the Architecture Documentation appear broken

### ISSUE THREAD

**Issue by nilanjan-samajdar** [open-ness/specs#22]
For example in  : https://github.com/open-ness/specs/blob/master/doc/architecture.md
Also in other places.

**Comment by amr-mokhtar** [comment]
Hi @nilanjan-samajdar, I couldn't find which image links are broken. Can you elaborate on which links that look broken?

**Comment by nilanjan-samajdar** [comment]
https://github.com/open-ness/specs/blob/master/doc/arch-images/openness_apponboard.png refered to in https://github.com/open-ness/specs/blob/master/doc/architecture.md.

I can't view the diagram in github

![image](https://user-images.githubusercontent.com/37446785/81058947-1a6d8580-8eed-11ea-824d-c998b26b5fd8.png)

**Comment by amr-mokhtar** [comment]
I logged out from GitHub and I confirm that I am able to see the images. Maybe try clearing your browser cache or use another web explorer?

**Comment by nilanjan-samajdar** [comment]
Thanks for your response, I'll check through some alternate means, please close the issue
