### ISSUE TITLE
error when running deploy_onprem.sh

### ISSUE THREAD

**Issue by xtycdd** [open-ness/specs#29]
I don't know what this error means. It appers in the process of deploying edgenode. What is online cpu? Maybe I did something wrong when prepare? 

TASK [machine_setup/configure_tuned : apply tuned profile] ****************************
task path: /home/git_repos/openness-experience-kits/roles/machine_setup/configure_tuned/tasks/configure_tuned.yml:43
fatal: [node01]: FAILED! => {
    "changed": true, 
    "cmd": [
        "tuned-adm", 
        "profile", 
        "realtime"
    ], 
    "delta": "0:00:00.228128", 
    "end": "2020-06-09 11:31:37.750965", 
    "rc": 1, 
    "start": "2020-06-09 11:31:37.522837"
}

STDERR:

Cannot load profile(s) 'realtime': Assertion 'isolated_cores contains online CPU(s)' failed.

MSG:

non-zero return code

**Comment by amr-mokhtar** [comment]
Hi @xtycdd, sorry for the delayed response. This seems to be related to misconfigured cores for tuned. How many cores do you have in your platform? The configuration assumes that you have more than 4 cores (https://github.com/otcshare/openness-experience-kits/blob/19b4127c739e2549cbf9de46145f1ae7090b6350/group_vars/edgenode_group/10-default.yml#L60-L63)

Another option is to disable `realtime` tuned profile installation if you don't need it. This can be done by setting flag `tuned_skip: true` in the same file shared above.
