### ISSUE TITLE
how to get yaml to deploy iterfaceservice pod of network edge node

### ISSUE THREAD

**Issue by Jaladi-Devika** [open-ness/specs#32]
Hi All,

How should I get original yaml to deploy interfaceservice pod of network edge node? actually i wan to deploy new interfaceservice image in edge node which will reflect same as original interface service which will come along edge node deployment.

tried below command to get yaml of original interfaceservice pod, am getting pod status also. But I need exact yaml to deploy interface service.

kubectl get pod <interfaceservice-pod-name> -n <namespace> -o yaml

**Comment by amr-mokhtar** [comment]
Interfaceservice is deployed as a k8s service. In order to get its original specs, use the below command:
```shell
kubectl get service interfaceservice -n openness -o yaml
```

**Comment by Jaladi-Devika** [comment]
@amr-mokhtar , actually this command to get the yaml of service. But we need interfaceservice pod yaml before deploying of interfaceservice image.
