### ISSUE TITLE
Kubectl command to delete pod permanently 

### ISSUE THREAD

**Issue by Jaladi-Devika** [open-ness/specs#34]
Hi All,

1.When I run kubectl delete pod <pod-name>, pod it getting restarted and stuck in below state.
openness               interfaceservice-ws5k9                       0/1     Init:0/1            0          30m

2. When run kubectl describe pod <pod-name>, below is the error

Events:
  Type     Reason                  Age   From                  Message
  ----     ------                  ----  ----                  -------
  Normal   Scheduled               21m   default-scheduler     Successfully assigned openness/interfaceservice-ws5k9 to worker-node
  Warning  FailedCreatePodSandBox  20m   kubelet, worker-node  Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "2e6d08ffc273d1ce9a6b57ee391a64a4c221824bfe2015116643cd14a0c74115" network for pod "interfaceservice-ws5k9": networkPlugin cni failed to set up pod "interfaceservice-ws5k9_openness" network: request ip return 500 configure nic failed add nic to ovs failed exit status 1: ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (Connection refused)
, failed to clean up sandbox container "2e6d08ffc273d1ce9a6b57ee391a64a4c221824bfe2015116643cd14a0c74115" network for pod "interfaceservice-ws5k9": networkPlugin cni failed to teardown pod "interfaceservice-ws5k9_openness" network: delete ip return 500 {
 "protocol": "",
 "address": "",
 "mac_address": "",
 "cidr": "",
 "gateway": "",
 "mtu": 0,
 "error": "del nic failed failed to delete ovs port exit status 1, ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (Connection refused)\n"
}]
  Normal  SandboxChanged  0s (x95 over 20m)  kubelet, worker-node  Pod sandbox changed, it will be killed and re-created.

Can you please suggest how to delete pod permanently and why pod is not running eventhough its restarted?

**Comment by amr-mokhtar** [comment]
`interfaceservice` is deployed as a k8s service. Therefore, you should use `kubectl delete service interfaceservice -n openness` instead.

**Comment by Jaladi-Devika** [comment]
[root@master-node Devika]# kubectl get pods --all-namespaces
NAMESPACE              NAME                                         READY   STATUS              RESTARTS   AGE
openness               interfaceservice-ws5k9                       0/1     Init:0/1            0          33m

want to delete this pod not the interfaceservice service.

**Comment by amr-mokhtar** [comment]
If you delete it, K8s scheduler will spin up a new one. K8s job is to ensure the services' pods are active and healthy.

**Comment by Jaladi-Devika** [comment]
Yes after deleting interfaceservice service and deployed my own interfaceservice service, I can able to communicate with my new pod. But still old interfaceservice pod is running.

Even after deleting service and then pod still pod is restarting again.

**Comment by amr-mokhtar** [comment]
Give it few seconds :)

**Comment by Jaladi-Devika** [comment]
still not deleted.
![image](https://user-images.githubusercontent.com/66933956/84986819-cf39ca00-b15c-11ea-9e6a-3b53334d77bf.png)

**Comment by amr-mokhtar** [comment]
I think that you have that resolved in #33 ?

**Comment by Jaladi-Devika** [comment]
But still the old pod running which i was highlighted in my previous comment.

**Comment by amr-mokhtar** [comment]
As advised earlier, you can only delete it by deleting the service it belongs to, e.g:
```shell
$ kubectl delete service interfaceservice -n openness
```
