### ISSUE TITLE
fmt.Printf logs are not avilable in kubectl logs command

### ISSUE THREAD

**Issue by Jaladi-Devika** [open-ness/specs#36]

**Comment by Jaladi-Devika** [comment]
Hi All,
I used the "fmt.Printf" to log the my own logs to STDOUT, but I could not find this output from the pod logs by using "kubectl logs". Could you please give me the reason and some possible solutions? Thank you so much.

**Comment by amr-mokhtar** [comment]
This query is out of scope for OpenNESS. You are encouraged to google for similar issues with logging in docker containers.
