### ISSUE TITLE
UPF implementation in OpenNESS Network Edge.

### ISSUE THREAD

**Issue by ishanVshah** [open-ness/specs#37]
Hi @amr-mokhtar 

I am referring below link to implement UPF on OpenNESS Network Edge.

https://github.com/open-ness/specs/blob/master/doc/core-network/openness_upf.md

how can we test the UPF and is there any simulator or test UPF available to install and check?

docker file "COPY 5g_upf_vpp ./5g_upf_vpp". from where i can get "5g_upf_vpp"?

**Comment by amr-mokhtar** [comment]
Hi @ishanVshah, is this issue is still active?

**Comment by ishanVshah** [comment]
yes

**Comment by ishanVshah** [comment]
Hi @amr-mokhtar 

i have following below link to implement UPF on Network Edge OpenNESS 20.06

https://github.com/open-ness/specs/blob/master/doc/core-network/openness_upf.md

**Issues:**

1. upf-cnf pod haven't extra sriov interface of 192.168.2.0/24 this CIDR range. please refer attached screenshot contains o/p of ip a.

2. not able to run "./run_upf.sh" file. refer attached screenshot.

![image](https://user-images.githubusercontent.com/59759055/89019137-7dc75200-d33a-11ea-9a4f-13bba190afb7.png)

**Comment by sudhir-intc** [comment]
Could you please confirm if you have enabled SRIOV as an additional CNI as described in https://github.com/open-ness/specs/blob/master/doc/enhanced-platform-awareness/openness-sriov-multiple-interfaces.md#sriov-for-network-edge. If you have successfully enabled SRIOV, please let us know if you were able to successfully allocate intel_sriov_dpdk device as described in step 7 of https://github.com/open-ness/specs/blob/master/doc/core-network/openness_upf.md#how-to-start.

**Comment by ishanVshah** [comment]
Hi @sudhir-intc  

we have enabled kube-OVN as a primary and SR-IOV as a secondary interface in OpenNESS NE kubernetes cluster.

![image](https://user-images.githubusercontent.com/59759055/89867851-6fe1be80-dbcf-11ea-9ef4-6ae64f316d52.png)

![image](https://user-images.githubusercontent.com/59759055/89867929-8d168d00-dbcf-11ea-9ebd-67795fa898de.png)

**Comment by sudhir-intc** [comment]
UPF-POD is bound to SRIOV VF with dpdk so you will not able to see the interface when you do "ip a" inside the pod.  
The UPF binary is not released through OpenNESS and its for that reason the run_upf.sh fails.  If you are having access to VPP based UPF, you could use the reference run_upf.sh to configure the VPP based UPF and bring up the UPF.

**Comment by ishanVshah** [comment]
Hi @sudhir-intc 

thanks for your quick reply !!

you mean to say that for this we must have a access of Intel® Distribution of OpenNESS ?

is my understanding correct ?

**Comment by sudhir-intc** [comment]
Currently with IDO too we don't distribute a UPF. 
We expect the customers/partners to have their own VPP based UPF available.

**Comment by ishanVshah** [comment]
@sudhir-intc 

Thanks Sudhir for your response and I appreciate if you have any link or document on opensource VPP based UPF available to run UPF on OpenNESS platform ?

@amr-mokhtar  requesting you to please close this ticket.
