### ISSUE TITLE
GTP filter Policy

### ISSUE THREAD

**Issue by akiskourtis** [open-ness/specs#43]
Hello,

Is there somewhere an example, if we want to forward packets sent from a UE behind the eNB to the LBP server?
I have experimented with the GTP filter field but I cannot get hold of how it works.

Thank you!

**Comment by akiskourtis** [comment]
Regarding this question, has anyone forwarded GTP packets to the LBP server? and what was his setup?
Is it supported or should I close this issue?

Best

**Comment by krishnajs** [comment]
No, this feature is not supported
