### ISSUE TITLE
dial : timeout exception.

### ISSUE THREAD

**Issue by ishanVshah** [open-ness/specs#46]
Hi Team,

I have installed and tested successfully OpenVINO application onboarding with OpenNESS 20.06

I have deleted OpenVINO consumer and producer pods post testing and now I am again created both pods and error occurred.

Please refer below screen shot. Can you please help me what is the issue ?

even i am not able to install kubernetes-dashboard on it. error is : no host to route.

![image](https://user-images.githubusercontent.com/59759055/88296828-cd939100-cd1c-11ea-8cfa-aa7a59cd25e4.png)

**Comment by amr-mokhtar** [comment]
This seems to be a networking issue. Are you using a proxy? Also, what is the status of the other pods?
What changed since the last time you deployed the application successfully?

**Comment by ishanVshah** [comment]
I didn't made any changes. 

I have deleted openvino application and installed Smart-City.

post deleted Smart-City because it was not worked and installing openvino but not able to create container.

some of the pods are frequently restarted and CrashLoopBackOff.

**Comment by ishanVshah** [comment]
Issue resolved. issue of adding route on machine so, pods are running on workers are not able to connect on master.

thanks for support !!

**Comment by ishanVshah** [comment]
Hi @amr-mokhtar 

i forgot to mention exact issue.

due to limitation of hardware, i used client-simulator running on a same cluster and when i changed the dns entry step in /etc/resolve.conf file, pods which are running on client-sim machine were stopped and eaa pod is run on the same client-sim machine.
