### ISSUE TITLE
My traffic generating host does not reach the OpenVino application in a Network Edge deployment

### ISSUE THREAD

**Issue by jalvarez96** [open-ness/specs#47]
Hello, I have been studying and testing the OpenNESS Network Edge architecture for a couple of months but I encounter the following problems and doubts when trying to deploy the OpenVino application following this documentation: [https://github.com/open-ness/specs/blob /master/doc/applications-onboard/network-edge-applications-onboarding.md#onboarding-openvino-application]

In my case, OpenNESS for Network Edge is fully installed and set up in a VPN with two nodes: 10.0.1.217 for the Controller and 10.0.1.120 for the Edge Node (node01). And the traffic generating host is at 10.20.0.201.

The specs say "From the Edge Controller, set up the interface service to connect the Edge Node's physical interface used for the communication between Edge Node and traffic generating host to OVS" Does this mean I cannot use node01 interface 10.0.1.120 and that I need a second physical interface on said node? In any case, I have a second physical interface on node01 to receive the streaming of the traffic generating host, and it is 10.0.0.120. But after the "kubectl interfaceservice attach ..." process I no longer have access to the machine through that interface, is this normal?

Another question: the specs say "The subnet 192.168.1.0/24 is allocated by Ansible playbook to the physical interface which is attached to the first edge node", "node jfsdm001 is bridged to subnet 192.168.1.0/24", "Ingress traffic originating from 192.168.1.0/24 can only reach the pods deployed on jfsdm001 ", so: as I said, my host is on ip 10.20.0.201, how can I add a new subnet or modify subnet 192.168.1.0/24 to that the traffic of my host is accepted?

Any answer or documentation that you can provide me to resolve these doubts will be welcome, thank you very much.

**Comment by krishnajs** [comment]
This ticket is open for a while now. Given that we have multiple releases since can you please check if this on the latest and open a ticket if it's still an issue.
