### ISSUE TITLE
Additional interface is not adding to the pod

### ISSUE THREAD

**Issue by Jaladi-Devika** [open-ness/specs#48]
HI Team,

Am trying to attach "macvlan" type interface to pod.

Here is my "networkattachmentdefinition" for additional interface.
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'

CNI config file::

{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name":"kube-ovn", "cniVersion":"0.3.1", "plugins":[ { "type":"kube-ovn", "server_socket":"/run/openvswitch/kube-ovn-daemon.sock" }, { "type":"portmap", "capabilities":{ "portMappings":true } } ] } ] }

Pod yml::

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: sgwc-deployment
  namespace: openness
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  selector:
    matchLabels:
      app: sgwc
  replicas: 1
  template:
    metadata:
      labels:
        app: sgwc
    spec:
      containers:
      - name: sgwc-container
        command: [ "/bin/bash" ]
        tty: true
        stdin: true
        image: vepc-sgw-c:1.0
        securityContext:
          privileged: true
        imagePullPolicy: Never
        ports:
        - containerPort: 40001
      dnsPolicy: "None"
      dnsConfig:
       nameservers:
        - 8.8.8.8

![image](https://user-images.githubusercontent.com/66933956/89488168-e728e400-d7c4-11ea-8eaf-67b29747e271.png)

Can you please let me if am missing any thing here?

**Comment by krishnajs** [comment]
This ticket is open for a while now. Given that we have multiple releases since can you please check if this on the latest and open a ticket if it's still an issue.
