### ISSUE TITLE
openness Controller deploy failed

### ISSUE THREAD

**Issue by Jaladi-Devika** [open-ness/specs#49]
Hi,

I am trying to deploy openness controller but failed at below step.
Can you please help on this? How to resolve?

TASK [kubernetes/cni/kubeovn/master : wait for running ovs-ovn & ovn-central pods] *******************************************************************
task path: /home/sysadmin/Murali/openness/openness-experience-kits/roles/kubernetes/cni/kubeovn/master/tasks/main.yml:149

./deploy_ne.sh controller last prints:
![image](https://user-images.githubusercontent.com/66933956/90318077-7ebbce80-df4b-11ea-8cda-908b7d37fe6d.png)

Pods status is:
![image](https://user-images.githubusercontent.com/66933956/90318062-43b99b00-df4b-11ea-88c7-e3778a0ead18.png)

Thanks & Regards,
Devika

**Comment by Jaladi-Devika** [comment]
![image](https://user-images.githubusercontent.com/66933956/90358193-f3d5f380-e072-11ea-8679-40fa04ea9b8a.png)
![image](https://user-images.githubusercontent.com/66933956/90358232-0cdea480-e073-11ea-881c-f693838af2a6.png)

Retry for pod creation failed.

**Comment by ishanVshah** [comment]
@Jaladi-Devika  as far as i know, docker images may be downloading and timeout ansible playbook at end.

you can pull all required images using docker pull command and then try it.

**Comment by Jaladi-Devika** [comment]
<img width="812" alt="vpu_1" src="https://user-images.githubusercontent.com/66933956/90391882-7bd7ef80-e0ab-11ea-96f2-e6e3bf523f4b.PNG">
<img width="821" alt="vpu_2" src="https://user-images.githubusercontent.com/66933956/90391889-7ed2e000-e0ab-11ea-8ea3-f475f2c7e691.PNG">

New issue found can you please help me on this?

**Comment by Jaladi-Devika** [comment]
@ishanVshah, playbook at end issue resolved after we cleanup and try to re-deploy again. But now new issue came.. have posted the screenshots above. can you check if you can help on this?

**Comment by ishanVshah** [comment]
Hi @Jaladi-Devika 
I am not sure but the issue is the version of golang. minimal version is required to install intel-device-plugin in kubernetes cluster is golang v1.13

you can skip this step if you are no need to use "intel-device-plugin".

set below parameter to false inside group_vars directory.
**k8s_device_plugins_enable: false**

**Comment by krishnajs** [comment]
This ticket is open for a while now. Given that we have multiple releases since can you please check if this on the latest and open a ticket if it's still an issue.
