### ISSUE TITLE
Userspace CNI in OpenNESS

### ISSUE THREAD

**Issue by ishanVshah** [open-ness/specs#50]
Hi @amr-mokhtar 

I am trying to deploy Userspace CNI POD in OpenNESS Network Edge kubernetes cluster.

I am followed below link for reference.
https://github.com/open-ness/specs/blob/master/doc/dataplane/openness-userspace-cni.md
but i am not able to see the two userspace cni interface available on pods. can you please help me on it.

**Comment by ishanVshah** [comment]
@amr-mokhtar can you please help me on this ?

**Comment by amr-mokhtar** [comment]
Hi @ishanVshah,
Userspace CNI does not provide a kernel interface in the pod.
As per our [documentation](https://www.openness.org/docs/doc/dataplane/openness-userspace-cni#virtual-interface-usage):
"Then you can use sockets available in your mount-point directory in your DPDK-enabled application deployed inside pod."
You will need to use a DPDK app to consume the socket file that was created by userspace CNI.

**Comment by krishnajs** [comment]
This ticket is open for a while now. Given that we have multiple releases since can you please check if this on the latest and open a ticket if it's still an issue.
