### ISSUE TITLE
Facing error while creating pod in sample-app

### ISSUE THREAD

**Issue by sushantsj** [open-ness/specs#56]
1.kubectl apply -f sample_policy.yml
2. kubectl create -f sample_producer.yml
In the second step, pod is not getting created and the error is ErrImageNeverPulled
[root@controller sample-app]# kubectl create -f sample_producer.yml
       deployment.apps/producer created
[root@controller sample-app]# kubectl get pods | grep producer
       producer-685fcbc569-bgv8c   0/1     _**ErrImageNeverPull**_   0          10s

**Comment by krishnajs** [comment]
This ticket is open for a while now. Given that we have multiple releases since can you please check if this on the latest and open a ticket if it's still an issue.
