### ISSUE TITLE
OpeNESS RAN documentation not accessible

### ISSUE THREAD

**Issue by Matheus-Garbelini** [open-ness/specs#63]
Hello, The `Open Source OpenNESS` documentation on RAN references intel documentation, but when contacting intel to acquire such documents, they can only provide them on `Intel distribution of OpenNESS` which is not publicly available.
https://github.com/open-ness/specs/blob/master/doc/reference-architectures/ran/openness_ran.md#references

How can we proceed?

Regards.

**Comment by archie951** [comment]
You can visit this link and request for IDO access. 
https://www.openness.org/products/intel-distribution

Regards,
Archit

**Comment by amr-mokhtar** [comment]
@Matheus-Garbelini If you are looking to get access to the FlexRAN documents mentioned in the References section, please note that [FlexRAN ](https://software.intel.com/content/www/us/en/develop/videos/an-overview-of-flexran-sw-wireless-access-solutions.html)is distributed through a different license. Please contact an Intel representative on that regard.
