### ISSUE TITLE
howto-images  links giving 404 errors

### ISSUE THREAD

**Issue by idirect-dev** [open-ness/specs#9]
When reviewing the documentation under
https://github.com/open-ness/specs/blob/master/doc/getting-started/on-premises/controller-edge-node-setup.md
  links to howto-images are not resolving.

https://github.com/open-ness/specs/blob/master/doc/applications-onboard/howto-images/

Example:
https://github.com/open-ness/specs/blob/master/doc/applications-onboard/howto-images/CreatingTrafficPolicy.png

**Comment by amr-mokhtar** [comment]
Hi @idirect-dev,
This has been fixed as of OpenNESS-20.03 release. Therefore, I am closing this issue.
